Repository epam/edp-codebase-operator, pull requests merged in 2024-10, with the labels that each got.

#137 docs: Update changelog file for release notes (#136)
  CHANGELOG.md
Labels: documentation

#138 feat: Add support for Bitbucket webhooks
  .golangci.yaml
  Makefile
  api/v1/codebase_types.go
  config/crd/bases/v2.edp.epam.com_codebases.yaml
  controllers/codebase/codebase_controller.go
  controllers/codebase/service/chain/common.go
  controllers/codebase/service/chain/delete_webhook.go
  controllers/codebase/service/chain/put_project.go
  controllers/codebase/service/chain/put_project_test.go
  controllers/codebase/service/chain/put_webhook.go
  deploy-templates/crds/v2.edp.epam.com_codebases.yaml
  docs/api.md
  go.mod
  go.sum
  hack/bitbucket_api.json
  hack/bitbucket_api_notes.md
  oapicfg.yaml
  pkg/gitprovider/auth_provider.go
  pkg/gitprovider/auth_provider_test.go
  pkg/gitprovider/bitbucket.go
  pkg/gitprovider/bitbucket/generated/bitbucket_client.generated.go
  pkg/gitprovider/bitbucket_test.go
  pkg/gitprovider/github.go
  pkg/gitprovider/github_test.go
  pkg/gitprovider/gitlab.go
  pkg/gitprovider/gitlab_test.go
  pkg/gitprovider/provider.go
  pkg/gitprovider/provider_test.go
  sonar-project.properties
Labels: enhancement

#142 chore: Update alpine base image to v3.18.9 (#141)
  Dockerfile
  deploy-templates/Chart.yaml
Labels: enhancement

#144 feat: Add support of clone/create strategy for Bitbucket
  controllers/codebase/service/chain/put_project.go
  pkg/gitprovider/bitbucket.go
  pkg/gitprovider/bitbucket_test.go
  pkg/gitprovider/errors.go
  pkg/gitprovider/gitlab.go
Labels: enhancement

#148 feat: Update Auto-stable deploy strategy logic
  api/v1/cdstagedeploy_types.go
  config/crd/bases/v2.edp.epam.com_cdstagedeployments.yaml
  controllers/cdstagedeploy/chain/create_pending_trigger_template.go
  controllers/cdstagedeploy/chain/create_pending_trigger_template_test.go
  controllers/cdstagedeploy/chain/factory.go
  controllers/cdstagedeploy/chain/process_pending_piperuns.go
  controllers/cdstagedeploy/chain/process_pending_piperuns_test.go
  controllers/cdstagedeploy/chain/process_trigger_template.go
  controllers/cdstagedeploy/chain/process_trigger_template_test.go
  controllers/cdstagedeploy/chain/resolve_status.go
  controllers/cdstagedeploy/chain/resolve_status_test.go
  controllers/codebaseimagestream/chain/put_cd_stage_deploy.go
  deploy-templates/crds/v2.edp.epam.com_cdstagedeployments.yaml
  docs/api.md
Labels: enhancement

#149 chore: Add set version block
  build/templates/applications/rpm-package/Makefile.tmpl
Labels: enhancement

#151 chore: Update current development version (#150)
  CHANGELOG.md
  deploy-templates/Chart.yaml
  deploy-templates/README.md
Labels: enhancement

#154 fix: Ignore extra labels in CodebaseImageStream for auto-deploy
  controllers/codebaseimagestream/chain/put_cd_stage_deploy.go
  controllers/codebaseimagestream/chain/put_cd_stage_deploy_test.go
Labels: bug

#152 chore: Update Pull Request Template (#21)
  pull_request_template.md
Labels: enhancement
