Repository epam/edp-codebase-operator, pull requests merged in 2024-06, with the labels that each got.

#73 feat: Implement queue for auto-deploy in pipelines
  api/v1/cdstagedeploy_types.go
  config/crd/bases/v2.edp.epam.com_cdstagedeployments.yaml
  config/rbac/role.yaml
  controllers/cdstagedeploy/cdstagedeploy_controller.go
  controllers/cdstagedeploy/cdstagedeploy_controller_test.go
  controllers/cdstagedeploy/chain/delete_cdstagedeploy.go
  controllers/cdstagedeploy/chain/delete_cdstagedeploy_test.go
  controllers/cdstagedeploy/chain/errors.go
  controllers/cdstagedeploy/chain/factory.go
  controllers/cdstagedeploy/chain/process_trigger_template.go
  controllers/cdstagedeploy/chain/process_trigger_template_test.go
  controllers/cdstagedeploy/chain/resolve_status.go
  controllers/cdstagedeploy/chain/resolve_status_test.go
  controllers/codebaseimagestream/chain/put_cd_stage_deploy.go
  controllers/codebaseimagestream/chain/put_cd_stage_deploy_test.go
  deploy-templates/crds/v2.edp.epam.com_cdstagedeployments.yaml
  deploy-templates/templates/role_kubernetes.yaml
  deploy-templates/templates/role_openshift.yaml
  docs/api.md
  go.mod
  main.go
  pkg/gitprovider/mocks/gitprojectprovider_mock.go
  pkg/gitprovider/mocks/provider_mock.go
Labels: enhancement

#75 fix: Set default pending status for CDStageDeploy
  api/v1/cdstagedeploy_types.go
  config/crd/bases/v2.edp.epam.com_cdstagedeployments.yaml
  deploy-templates/crds/v2.edp.epam.com_cdstagedeployments.yaml
  docs/api.md
Labels: bug

#77 chore: Update argocd diff
  deploy-templates/templates/clusterrole_openshift.yaml
  deploy-templates/templates/clusterrolebinding_openshift.yaml
  deploy-templates/templates/role_openshift.yaml
  deploy-templates/templates/rolebinding_admin_openshift.yaml
  deploy-templates/templates/rolebinding_openshift.yaml
Labels: dependencies

#78 fix: Incorrect handling of parallel CDStageDeploy
  api/v1/cdstagedeploy_types.go
  config/crd/bases/v2.edp.epam.com_cdstagedeployments.yaml
  controllers/cdstagedeploy/chain/resolve_status.go
  controllers/codebaseimagestream/chain/factory.go
  controllers/codebaseimagestream/chain/handler/codebase_image_stream_handler.go
  controllers/codebaseimagestream/chain/put_cd_stage_deploy.go
  controllers/codebaseimagestream/chain/put_cd_stage_deploy_test.go
  controllers/codebaseimagestream/codebaseimagestream_controller.go
  deploy-templates/crds/v2.edp.epam.com_cdstagedeployments.yaml
  docs/api.md
Labels: bug

#82 chore: Update current development version
  CHANGELOG.md
  deploy-templates/Chart.yaml
  deploy-templates/README.md
Labels: enhancement
